export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CURRENT_USER_INFO = "SET_CURRENT_USER_INFO";

export const SET_ERRORS = "SET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const CREATE_NEW_PRODUCT = "CREATE_NEW_PRODUCT";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";
export const FAVORITE_PRODUCT = "FAVORITE_PRODUCT";

export const CREATE_NEW_QUESTION = "CREATE_NEW_QUESTION";
export const CREATE_NEW_ANSWER = "CREATE_NEW_ANSWER";

export const GET_MY_PRODUCTS = "GET_MY_PRODUCTS";
