export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CURRENT_USER_INFO = "SET_CURRENT_USER_INFO";
export const SET_CURRENT_USER_LOADING = "SET_CURRENT_USER_LOADING";
export const SET_CURRENT_USER_INFO_LOADING = "SET_CURRENT_USER_INFO_LOADING";

export const SET_ERRORS = "SET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const CREATE_NEW_PRODUCT = "CREATE_NEW_PRODUCT";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const SET_PRODUCTS_LOADING = "GET_PRODUCTS_LOADING";
export const GET_PRODUCT = "GET_PRODUCT";
export const FAVORITE_PRODUCT = "FAVORITE_PRODUCT";

export const CREATE_NEW_QUESTION = "CREATE_NEW_QUESTION";
export const CREATE_NEW_ANSWER = "CREATE_NEW_ANSWER";

export const GET_MY_PRODUCTS = "GET_MY_PRODUCTS";
export const GET_MY_FAVORITES = "GET_MY_FAVORITES";
export const GET_MY_INITIATES = "GET_MY_INITIATES";
export const GET_MY_OFFERS = "GET_MY_OFFERS";
export const SET_MY_PRODUCTS_LOADING = "SET_MY_PORDUCTS_LOADING";
export const SET_MY_FAVORITES_LOADING = "SET_MY_FAVORITES_LOADING";
export const SET_MY_INITIATES_LOADING = "SET_MY_INITIATES_LOADING";
export const SET_MY_OFFERS_LOADING = "SET_MY_OFFERS_LOADING";
