export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const SET_ERRORS = "SET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const CREATE_NEW_PRODUCT = "CREATE_NEW_PRODUCT";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";
